# App Name & Port
spring.application.name=counselor
server.port=8080

# Enable H2 Database Console (view your database in the browser at http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:counselordb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate Auto-DDL Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Swagger UI Custom Endpoint Path
springdoc.swagger-ui.path=/swagger-ui.html